### ISSUE TITLE
support tacticity

### ISSUE THREAD

**Issue by micaela-matta** [matta-research-group/SwiftPol#4]
swiftpol should be able to support different polymer [tacticities](https://en.wikipedia.org/wiki/Tacticity)

**Comment by hannaomi** [comment]
You can now control tacticity in your ensemble, with an addition to the build.polymer_system() function.
Include the variable stereoisomerism_input = ['X', Y, 'Z'] in your build command. Defaults to None
where:
X = monomer to replace (string)
Y = frequency of stereoisomer to introduce (float)
Z = monomer SMILES of stereoisomer (string)

e.g.
stereoisomerism_input=['A', 0.5, 'O[C@@H](C)C(=O)O[I]']

alternatively, to perform this function on your user-defined sequence string, use [build.introduce_stereoisomers().](https://matta-research-group.github.io/SwiftPol/api.html#swiftpol.build.introduce_stereoisomers)
